name: flutter_frontend
description: The frontend for the lobevent app written in flutter

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # generates routes and handles all the navigation stuff
  auto_route: ^1.0.2

  # annotations for json code generation
  json_annotation: ^4.0.1

  # annotations for freezed data and union classes code generation
  freezed_annotation: ^0.14.1

  # dartz for a ton of useful utils (like Either type and so on)
  dartz: ^0.10.0-nullsafety.1  

  # standard dart http library
  http: ^0.13.1

  # bloc library in general (Cubit and Bloc)
  bloc: ^7.0.0

  # flutter bloc specific widgets like BlocConsumer
  flutter_bloc: ^7.0.0

  # safe state of bloc/cubit
  hydrated_bloc: ^7.0.0

  # safe on local
  path_provider: ^2.0.2

  # get_it dependency injection for flutter
  get_it: ^6.0.0

  # uuid for the user objects (and probably more later)
  uuid: ^3.0.2

  # this plugin will handle the google part of signing in with google
  google_sign_in: ^5.0.1

  # this plugin will handle the apple part of signing in with apple
  sign_in_with_apple: ^3.0.0

  # we need to check that the iOS version is at least 13 since 12 won't support apple sign in
  device_info: ^2.0.0

  ###
  # start firebase related stuff
  ###
  # use firebase core to initialize app
  firebase_core: ^1.0.2
  
  # firebase auth for the authentication with firebase
  firebase_auth: ^1.0.1
  ###
  # end firebase related stuff
  ###

  #string interpolation
  sprintf: ^6.0.0
  #searching bar
  material_floating_search_bar: ^0.3.4

  # Equality Comparisons of objects
  equatable: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2

  # generator for the auto route plugin
  auto_route_generator: ^1.0.2

  # data and union classes generator
  freezed: ^0.14.1+1

  # json serializable code generation
  json_serializable: ^4.1.0

  # mock libary to mock dependencies
  mockito: ^5.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
