name: flutter_frontend
description: The frontend for the lobevent app written in flutter

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  freezed_annotation: ^0.12.0
  dartz: ^0.9.2
  json_annotation: ^3.1.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.12.1
  json_serializable: ^3.5.0
flutter:
  uses-material-design: true
