name: test_and_build
on:
  push

jobs:

  analyze-test-build:
    name: Analyze, test, and build the app
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: ubuntu-latest
          build-target: appbundle
        - os: macos-latest
          build-target: ios --no-codesign
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: flutter_app
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v2
      - name: Install flutter using the stable channel
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Print info
        run: flutter --version
      - name: Fetch dependencies
        run: flutter pub get
      - name: Run code-generation
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze code
        run: flutter analyze --no-fatal-infos
      - name: Run tests
        run: flutter test
      - name: Build for Android
        run: flutter build appbundle
      - name: Build for iOS
        if: matrix.os == 'macos-latest'
        run: flutter build ${{ matrix.build-target }}
