name: test_and_build
on:
  push

jobs:

  test_and_build:
    name: Test the flutter app and build it (should always pass)
    runs-on: macos-latest # needs to be macos otherwise flutter can't build for iOS
    defaults:
      run:
        working-directory: flutter_app
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v2
      - name: Install flutter using the stable channel
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Print info
        run: flutter --version
      - name: Fetch dependencies
        run: flutter pub get
      - name: Run code-generation
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze code
        run: flutter analyze --no-fatal-infos
      - name: Run tests
        run: flutter test --no-pub --coverage
      - name: Build for Android
        run: flutter build appbundle
      - name: Build for iOS
        run: flutter build ios --no-codesign
